[grid] # rank and lambda values to be evaluated in grid search (all-by-all)
ranks = [15]
lambdas = [
    [1.0, 0.0, 0.0], [2.0, 0.0, 0.0], [3.0, 0.0, 0.0], [4.0, 0.0, 0.0], [5.0, 0.0, 0.0], 
    [6.0, 0.0, 0.0], [7.0, 0.0, 0.0], [8.0, 0.0, 0.0], [9.0, 0.0, 0.0], [10.0, 0.0, 0.0], 
    [11.0, 0.0, 0.0], [12.0, 0.0, 0.0], [13.0, 0.0, 0.0], [14.0, 0.0, 0.0], [15.0, 0.0, 0.0], 
    [16.0, 0.0, 0.0], [17.0, 0.0, 0.0], [18.0, 0.0, 0.0], [19.0, 0.0, 0.0], [20.0, 0.0, 0.0], 
    [21.0, 0.0, 0.0], [22.0, 0.0, 0.0], [23.0, 0.0, 0.0], [24.0, 0.0, 0.0], [25.0, 0.0, 0.0], 
    [26.0, 0.0, 0.0], [27.0, 0.0, 0.0], [28.0, 0.0, 0.0], [29.0, 0.0, 0.0], [30.0, 0.0, 0.0], 
    [31.0, 0.0, 0.0], [32.0, 0.0, 0.0], [64.0, 0.0, 0.0]
]

[params] # other parameters passed to the SparseCPTensor model, constant across grid search
nonneg_modes = [1, 2]
tol = 0.00001
n_iter_max = 2000
n_initializations = 5 

[script] # other script parameters including output directory, bootstraps, etc.
outdir = "../../data/4-fitting/"
n_bootstraps = 100
replicates = ['A', 'B', 'C']
max_processes = 28
seed = 4791  
