[grid] # rank and lambda values to be evaluated in grid search (all-by-all)
ranks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
lambdas = [[10.0, 0.0, 0.0], [15.0, 0.0, 0.0]]

[params] # other parameters passed to the SparseCPTensor model, constant across grid search
nonneg_modes = [1, 2]
tol = 0.00001
n_iter_max = 2000
n_initializations = 5 

[script] # other script parameters including output directory, bootstraps, etc.
outdir = "../../data/4-fitting/"
n_bootstraps = 10
replicates = ['A', 'B', 'C']
max_processes = 28
seed = 7394  